### ISSUE TITLE
gradle:5.4.1-jdk8-alpine doesn't work with GitLab pipeline

### ISSUE THREAD

**Issue by daggerok** [keeganwitt/docker-gradle#125]
Hello

My Gitlab pipeline is failing when I'm using `gradle:5.4.1-jdk8-alpine` image

```yaml
build frontend ui:
  image: gradle:5.4.1-jdk8-alpine
  stage: build
  cache:
    paths:
      - frontend/.gradle
      - frontend/ui/.npm
      - frontend/ui/node_modules
  script:
    - cd $CI_PROJECT_DIR/frontend
    - ./gradlew npm_install
    - ./gradlew npm_run_build
  artifacts:
    paths:
      - frontend/src/main/resources/public
```

error:

```
> Task :npmSetup FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':npmSetup'.
> A problem occurred starting process 'command '/builds/sigmasoftware/dumb-recruiters/frontend/build/nodejs/node-v12.13.1-linux-x64/bin/node''
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2m 8s
2 actionable tasks: 2 executed
```

I'm using gradle node plugin which should download and install needed nodejs distribution (tasks `nodeSetup` and `npmSetup`), and seems like after installing nodejs binaries, these binaries couldn't be found in path on next run. Strange but if I'm using `gradle:jdk8` image instead:

```yaml
build frontend ui:
  image: gradle:jdk8
```
everything is working as expected. and nodejs binaries can be installed without problems:

```bash
> Task :npmSetup
/builds/sigmasoftware/dumb-recruiters/frontend/build/npm/npm-v6.9.0/bin/npm -> /builds/sigmasoftware/dumb-recruiters/frontend/build/npm/npm-v6.9.0/lib/node_modules/npm/bin/npm-cli.js
/builds/sigmasoftware/dumb-recruiters/frontend/build/npm/npm-v6.9.0/bin/npx -> /builds/sigmasoftware/dumb-recruiters/frontend/build/npm/npm-v6.9.0/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
```

Updated: found [this (maybe) related](https://github.com/srs/gradle-node-plugin/issues/261) problem. Can you please also add `glibc` in your alpine images? Or it's in reality needed only because I'm using gradle node plugin?

Thanks

---
Regards
