### ISSUE TITLE
git upgrade

### ISSUE THREAD

**Issue by daroga0002** [keeganwitt/docker-gradle#151]
Currently image is using git incoming from default repository, which is:
```
# git --version
git version 2.17.1
```

this is quite legacy version which doesnt have a lot of features, what is more  GitHub actions Checkout require:
```
.............
Run actions/checkout@v2
/usr/bin/docker exec  36dda5583e39e95e38d956eb652aabff91ab298209cc2d4b7e2beaf1f556b489 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: ************
Getting Git version info
Deleting the contents of '************'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
...........
```

this causing that some gradle plugins are not working in my CI build as I download is performed using GitHub REST API.

This is issue occuring only when you want use this image in GitHub action for example using definition:
```
name: Repo CI
on: push
jobs:
  CI:
    runs-on: self-hosted
    container: 
      image: gradle:6.6.1-jdk8
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Build and test task
        run:  |
          ./gradlew build
          ./gradlew versionFile # this is failing as I am missing .git dir as action used REST API to download content
``` 

Can we update git inside this docker image to something newer?
